GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFkYW4iLCJpYXQiOjE2ODAwODYxODZ9.vzeFM6rO7ivJrHZGINKoQlqUoozO4qbP-peQUA7ktsE
###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "Madan"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
"username": "Adit"
}